update

diff --git a/scripts/myservice/Dockerfile b/scripts/myservice/Dockerfile
--- a/scripts/myservice/Dockerfile
+++ b/scripts/myservice/Dockerfile
@@ -1,27 +1,30 @@
-FROM adoptopenjdk/openjdk11:alpine-slim as backend
+#FROM openjdk:11-jre-slim as builder
+#build #1
+#FROM adoptopenjdk/openjdk11:alpine-slim as builder
+FROM 192.168.9.10:5000/openjdk11:alpine-slim as builder
+WORKDIR application
+ARG JAR_FILE=target/*.jar
+COPY ${JAR_FILE} application.jar
+RUN java -Djarmode=layertools -jar application.jar extract
 
-WORKDIR /opt/app
+#build #2
+FROM 192.168.9.10:5000/openjdk11:alpine-slim
 
-# Tomcat default port
-#              "-Dspring.profiles.active=local", \
-EXPOSE 8080
+#ENV TZ=Asia/Shanghai LC_ALL='zh_CN.UTF-8'
+#
+#RUN apk add --no-cache curl jq tzdata && \
+#    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
+#    apk del tzdata
+#
+#EXPOSE ${PORT:-8080}
+#HEALTHCHECK --start-period=15s --interval=1m --timeout=10s --retries=5 \
+#            CMD curl --silent --fail --request GET http://localhost:${PORT:-8080}/app/actuator/health \
+#                | jq --exit-status '.status == "UP"' || exit 1
 
-ENV TZ=Asia/Shanghai LC_ALL='zh_CN.UTF-8'
+WORKDIR application
+COPY --from=builder application/dependencies/ ./
+COPY --from=builder application/spring-boot-loader/ ./
+COPY --from=builder application/snapshot-dependencies/ ./
+COPY --from=builder application/application/ ./
 
-RUN apk add --no-cache curl jq tzdata && \
-    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
-    apk del tzdata
-
-COPY ./target/myservice-0.0.7-SNAPSHOT.jar /opt/app/app.jar
-
-#    -  -Djava.security.egd  Tomcat
-#      (https://wiki.apache.org/tomcat/HowTo/FasterStartUp#Entropy_Source)
-
-ENTRYPOINT ["java", \
-            "-Djava.security.egd=file:/dev/./urandom", \
-            "-jar", "/opt/app/app.jar" \
-]
-
-HEALTHCHECK --start-period=15s --interval=1m --timeout=10s --retries=5 \
-            CMD curl --silent --fail --request GET http://localhost:8080/app/actuator/health \
-                | jq --exit-status '.status == "UP"' || exit 1
+ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
